### ISSUE TITLE
Announcer not working

### ISSUE THREAD

**Issue by mlama007** [vue-a11y/vue-announcer#15]
Recently tried to update my project and Vue-announcer is not working. The demo on the docs is also not working. I see some updates were made, could this have broken something?

**Comment by ktquez** [comment]
Hello @mlama007, how are you?

I'm going to do a new test and see what's going on, okay?
I will answer you as soon as possible.

Thank you for using and contributing.

**Comment by ktquez** [comment]
I noticed some delay problems, mainly being used with Vuepress.

I'm launching a new version with some improvements and the possibility to customize the politeness settings.

**Comment by ktquez** [comment]
@mlama007 

I would be happy to hear from you about v2 that fixes some problems and covers other scenarios.
We are opening a conversation at https://github.com/vue-a11y/vue-announcer/pull/17

Your contribution would be incredible.

**Comment by ktquez** [comment]
Hello Maria, the [v2](https://vue-announcer-v2.surge.sh/) of the announcer is available, would you like to do some more tests and see if it's ok now?

It has a section of [browser testing](https://vue-announcer-v2.surge.sh/guide/support.html) with screen readers, if you can help us with that, it will be perfect.
