### ISSUE TITLE
Politeness settings

### ISSUE THREAD

**Issue by RCX07** [vue-a11y/vue-announcer#16]
Hi. I really like the plugin, it makes things easier for developers, with less expertise in accessibility.

The only issue I have with it is, that you can't change the politeness settings of the aria-live attribute. I've already did this locally in a fork, where I pass the politeness as a prop and the default value of this prop would be polite so it won't cause any breaking changes.

If you're interested in adding this feature, I can submit a PR. I have it ready to go.

**Comment by RCX07** [comment]
I've thought about the solution I've proposed and I've realized, that doing this by passing a prop just doesn't feel right. Because it's a plugin it would be much more appropriate to use the plugin options to set the politeness settings. I've already changed this. Now I'm working on the message level adjustment of the politeness settings, which raise a couple of timing issues that I've got to figure out.

**Comment by ktquez** [comment]
Hello Kádár, how are you?

I would love to see what you have done with improvements and customization, and if you wish, it would be incredible to receive your pull-request.

Thank you for using and contributing to the vue-announcer.

**Comment by RCX07** [comment]
Hey. I'll hit you up with a PR on Monday! I've made a couple of changes. But it seems to be working alright, without causing any breaking changes in the API. I have to update the unit tests, and then I'm ready to go!

**Comment by ktquez** [comment]
I was already working on a new version to fix some problems, update packages and fix a problem when using vue-Announcer on vuepress.

Then I added your suggestion to make it easier to customize the politeness settings.

Documentation for v2 is still missing, but if you can contribute more ideas it will be perfect https://github.com/vue-a11y/vue-announcer/pull/17

**Comment by ktquez** [comment]
Hello @RCX07  how are you?

You could try [v2](https://github.com/vue-a11y/vue-announcer/tree/v2.0.0) and if you want to suggest some more feature or send some PR, we will be very grateful.

Thanks for using.
