### ISSUE TITLE
Should vue be a devDependency?

### ISSUE THREAD

**Issue by koernchen02** [vue-a11y/vue-announcer#24]
Hi all!

Since the checkout of the @next branch, vue is explicitly required as a dependency and I don't understand the reasoning behind the decision.

I think a lot of users already use their preferred vue version via an application-level package.json.

I'm currently using @vue-a11y/announcer in a quasar-framework based project which stubs explicit dependencies on a regular basis. (based on success of automated build and test processes etc.)

Quasar is currently "stubbed" to v3.1.1 and since announcer does not require vue as a devDependency (or peerDependency) yarn/npm creates a node_module folder with the latest vue package inside the @vue-a11y/XYZ directories which is at the moment v3.1.2. which breaks our application build processes.
As a devDependency announcer (and eg. the skip-to package) should be totally fine with v3.1.1 which gets explicitly installed via quasars hard dependency.

Best regards and thanks a lot for your efforts in making vue so much more accessible!

**Comment by ktquez** [comment]
Thanks @koernchen02 
Fixed in [v3.1.5](https://github.com/vue-a11y/vue-announcer/tree/v3.1.5)

**Comment by koernchen02** [comment]
@ktquez Thanks for getting back and fixing the problem. I did not want to make many seperate issues, but the same thing applies for the skip-to package! Would be awesome if you could take care of that too!

Much appreciated Thanks a lot!

**Comment by ktquez** [comment]
@koernchen02 
I'll do it, thanks!
